name: Build GoShield Builder

on:
  
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Builder on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Go Environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.20' # [关键修改] 强制使用 Go 1.20 编译，保障 Windows 7 兼容性
        cache: true

    - name: Build Builder Executable
      run: |
        mkdir build
        go build -ldflags "-s -w" -o build/Builder.exe ./cmd/builder

    - name: Upload Builder Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GoShield-Builder
        path: build/Builder.exe
        compression-level: 6
